# Generated by Django 3.0.4 on 2020-03-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Type', models.CharField(max_length=50)),
                ('QuantiteStock', models.IntegerField()),
                ('SeuilMinimum', models.IntegerField()),
            ],
        ),
    ]
